schema_version = "1.0.0"

id = "py2gn"
version = "0.1.0"
name = "py2gn"
tagline = "Compile Python functions into Geometry Nodes groups"
maintainer = "Hayk Hakobyan <haykh.astro@gmail.com>"
type = "add-on"

tags = ["Geometry Nodes", "Node", "Text Editor", "Development"]

blender_version_min = "5.2.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 Hayk Hakobyan"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/tests/",
  "/docs/",
  "/.vscode/",
  "/scratch/",
  "/scripts/",
  "/tools/",
  "/.venv/",
  "/.ruff_cache/",
  "/pyrefly.toml",
  "/ruff.toml",
  "/requirements.txt",
  "/README.md",
  "/.gitignore",
  "/*.ps1",
  "/*.sh",
]
