"""Write editor configuration next to a function file (pyrefly, ruff, VS Code)."""

from __future__ import annotations

import json
import os

ADDON_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def venv_python() -> str | None:
    """The add-on checkout's .venv interpreter (has fake-bpy-module, ruff, pyrefly and `py2gn` on its path)."""
    for rel in (("Scripts", "python.exe"), ("bin", "python")):
        path = os.path.join(ADDON_ROOT, ".venv", *rel)
        if os.path.isfile(path):
            return path
    return None


def setup_folder(folder: str) -> tuple[list[str], list[str]]:
    """Create config files in ``folder``; existing files are never touched. Returns (written, skipped)."""
    py = venv_python()
    if py is None:
        raise FileNotFoundError(f"no .venv in {ADDON_ROOT}; run scripts/setup_venv.ps1 (or .sh) there first")
    py = py.replace("\\", "/")
    files = {
        "pyrefly.toml": (
            "# generated by py2gn: full type checking for py2gn function files\n"
            f'python-interpreter-path = "{py}"\n'
            "\n"
            "[errors]\n"
            "# allows the optional `-> outputs(...)` / `-> {...}` return annotations\n"
            "invalid-annotation = false\n"
        ),
        "ruff.toml": (
            "# generated by py2gn\n"
            "[lint]\n"
            "# `gn.tVec(...)` parameter defaults are compile-time literals, not calls\n"
            'ignore = ["B008"]\n'
        ),
        os.path.join(".vscode", "settings.json"): json.dumps(
            {
                "python.defaultInterpreterPath": py,
                # resolve `py2gn` and the bpy stubs even if another interpreter is selected (Pylance)
                "python.analysis.extraPaths": [
                    os.path.dirname(ADDON_ROOT).replace("\\", "/"),
                    os.path.join(ADDON_ROOT, ".venv", "Lib", "site-packages").replace("\\", "/"),
                ],
            },
            indent=2,
        )
        + "\n",
    }
    written, skipped = [], []
    for rel, body in files.items():
        path = os.path.join(folder, rel)
        if os.path.exists(path):
            skipped.append(rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
        written.append(rel)
    return written, skipped
